models:
  - name: portfolio
    description: Case files finance data mart
    columns:
        - name: cfid
          description: ID for the case file
          label: Case File ID
          tests:
              - unique
        - name: debtor_id
          description: ID of the debtor
          label: Debtor ID
        - name: customers
          description: Names of the customers
          label: Customer Names

        - name: product
          description: Title of the product
          label: Product Title
          tests:
              - not_null
              - unique
        - name: organization
          description: Name of the organization
          label: Organization Name
          tests:
              - not_null
              - unique
        - name: organization_id
          description: ID of the organization
          label: Organization ID
          tests:
              - not_null
              - unique
        - name: user
          description: Full name of the user
          label: USer Full Name
          tests:
              - not_null

        - name: user_id
          description: ID of the user
          label: User ID
          tests:
              - unique

        - name: team
          description: Title of the team
          label: Team Title
          tests:
              - not_null

        - name: team_id
          description: ID of the team
          label: Team ID
          tests:
            - not_null
            - unique

        - name: debt_type
          description: Title of the debt type
          label: Debt Type Title
          tests:
            - not_null

        - name: branch
          description: Title of the branch
          label: Branch Title
          tests:
            - not_null
            - unique

        - name: branch_id
          description: ID of the branch
          label: Branch ID
          tests:
              - unique
              - not_null

        - name: contact_status
          description: Title of the contact status
          label: Contact Status Title
          tests:
            - not_null

        - name: contact_type
          description: Title of the contact type
          label: Contact Type Title
          tests:
            - not_null

        - name: bucket
          description: Title of the bucket
          label: Bucket Title
          tests:
            - not_null

        - name: delinquency
          description: Title of the delinquency reason
          label: Delinquency Reason Title
          tests:
            - not_null

        - name: dispute
          description: Title of the dispute reason
          label: Dispute Reason Title
          tests:
            - not_null
        
        - name: loan_id
          description: ID of the loan
          label: Loan ID
          tests:
            - not_null
            - unique

        - name: account_state
          description: State of the account
          label: Account State
          tests:
            - not_null

        - name: principal_amount
          description: Principal amount of the loan
          label: Principal Amount
          tests:
            - not_null

        - name: loan_amount
          description: Loan amount
          label: Loan Amount
          tests:
            - not_null

        - name: arrears
          description: Arrears on the loan
          label: Arrears
          tests:
            - not_null

        - name: balance
          description: Balance of the loan
          label: Balance
          tests:
            - not_null

        - name: total_payments
          description: Total payments made on the loan
          label: Total Payments
          tests:
            - not_null

        - name: account_no
          description: Account number
          label: Account Number
          tests:
            - not_null
            - unique

        - name: customer_no
          description: Customer number
          label: Customer Number
          tests:
            - not_null
            - unique

        - name: dpd
          description: Days past due
          label: Days Past Due
          tests:
            - not_null

        - name: taken_date
          description: Date when the loan was taken
          label: Loan Taken Date
          tests:
            - not_null
        
        - name: due_date
          description: Due date of the loan
          label: Loan Due Date
          tests:
            - not_null

        - name: allocated
          description: Allocation status of the loan
          label: Allocation Status
          tests:
            - not_null

        - name: traction
          description: Traction status of the loan
          label: Traction Status
          tests:
            - not_null

        - name: score
          description: Score of the loan
          label: Loan Score
          tests:
            - not_null

        - name: last_action_date
          description: Date of the last action taken on the loan
          label: Last Action Date
          tests:
            - not_null

        - name: next_action_date
          description: Date of the next action to be taken on the loan
          label: Next Action Date
          tests:
            - not_null
            
        - name: created_date
          description: Date when the loan was created
          label: Created Date
          tests:
            - not_null

