--- case_files

with case_files as (
    select
        id as case_file_id,
        {{ coalesce_to_uuid('debtor_id') }},
        loan_id,
        {{ coalesce_to_uuid('organization_id') }},
        {{ coalesce_to_uuid('user_id') }},
        {{ coalesce_to_uuid('team_id') }},
        {{ coalesce_to_uuid('closure_reason_id') }},
        {{ coalesce_to_uuid('last_action_id') }},
        {{ coalesce_to_uuid('next_action_id') }},
        {{ coalesce_to_uuid('product_id') }},
        {{ coalesce_to_uuid('sub_product_id') }},
        -- {{ coalesce_to_uuid('client_id') }},
        -- {{ coalesce_to_uuid('partner_id') }},
        {{ coalesce_to_uuid('bucket_id') }},
        {{ coalesce_to_uuid('currency_id') }},
        {{ coalesce_to_uuid('country_id') }},
        {{ coalesce_to_uuid('branch_id') }},
        {{ coalesce_to_uuid('debt_type_id') }},
        {{ coalesce_to_uuid('collection_stage_id') }},
        {{ coalesce_to_uuid('collection_sub_stage_id') }},
        {{ coalesce_to_uuid('contact_status_id') }},
        {{ coalesce_to_uuid('contact_type_id') }},
        {{ coalesce_to_uuid('delinquency_reason_id') }},
        {{ coalesce_to_uuid('dispute_reason_id') }},
        {{coalesce_to_uuid('workflow_task_id')}},
        COALESCE(interest_amount, 0) AS interest_amount,
        COALESCE(interest_rate, 0) AS interest_rate,
        COALESCE(emi, 0) AS emi,
        COALESCE(waived, 0) AS waived,
        COALESCE(waived_balance, 0) AS waived_balance,
        COALESCE(discount, 0) AS discount,
        COALESCE(discount_balance, 0) AS discount_balance,
        COALESCE(overdraw_charges, 0) AS overdraw_charges,
        COALESCE(penalty_amount, 0) AS penalty_amount,
        COALESCE(ledger_fee, 0) AS ledger_fee,
        COALESCE(agency_commission, 0) AS agency_commission,
        COALESCE(principal_amount, 0) AS principal_amount,
        COALESCE(loan_amount, 0) AS loan_amount,
        COALESCE(arrears, 0) AS arrears,
        COALESCE(balance, 0) AS balance,
        COALESCE(amount_repaid, 0) AS amount_repaid,
        COALESCE(total_payments, 0) AS total_payments,
        COALESCE(installment_amount, 0) AS installment_amount,
        COALESCE(installment_balance, 0) AS installment_balance,
        COALESCE(next_installment_amount, 0) AS next_installment_amount,
        COALESCE(last_paid_amount, 0) AS last_paid_amount,
        COALESCE(is_new_allocation, false) AS is_new_allocation,
        COALESCE(score, 0) AS score,
        COALESCE(traction, 0) AS traction,
        COALESCE(closed, false) AS closed,
        COALESCE(allocated, false) AS allocated,
        context,
        account_state,        
        account_no,
        service_account_no,
        contract_no,
        customer_no,
        has_manual_update,
        case_branch,
        batch_no,
        dpd,
        loan_term,
        term_fees,       
        allocation_type,
        is_visible,        
        recommendation_id,
        created_by,
        updated_by,
        closed_by,
        extra_attributes,
        loan_count,
        workflow_task_type,
        {{ coalesce_to_date('next_installment_date')}},
        {{ coalesce_to_date('approval_date')}},
        {{ coalesce_to_date('disbursment_date')}},
        {{ coalesce_to_date('loan_taken_date')}},
        {{ coalesce_to_date('loan_due_date')}},
        {{ coalesce_to_date('last_synced_at') }},
        {{ coalesce_to_date('traction_date') }},
        {{ coalesce_to_date('last_action_date') }},
        {{ coalesce_to_date('next_action_date') }},
        {{ coalesce_to_timestamp('last_paid_date')}},
        {{ coalesce_to_timestamp('closed_at') }},
        {{ coalesce_to_timestamp('reactivated_at') }},
        {{ coalesce_to_timestamp('created_at') }},
        {{ coalesce_to_timestamp('updated_at')}}
        

    from
        {{ source(var('source_db'), 'case_files') }} 
    where
        deleted_at is null
)

select * from case_files