name: Build DBT Service
on:
  push:
    paths:
      - "/**"
      - ".github/workflows/smartcollect.yml"
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: registry.digitalocean.com
      IMAGE_NAME: crafted/dbt-lineage:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DO_ACCESS_TOKEN }}
          password: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Build and push
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
